package view;

public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form guiSistema_empleados_menu
     */
    public VentanaMenu() {
        initComponents();
        // this for center in to the screen the app
        this.setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelBackgroundTitle1 = new org.edisoncor.gui.label.LabelBackgroundTitle();
        jcMousePanel2 = new jcMousePanel.jcMousePanel();
        labelHeader1 = new org.edisoncor.gui.label.LabelHeader();
        btnPlanilla = new org.edisoncor.gui.button.ButtonTask();
        btnRecibo = new org.edisoncor.gui.button.ButtonTask();
        btnPlanilla1 = new org.edisoncor.gui.button.ButtonTask();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jcMousePanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/menu.jpg"))); // NOI18N

        labelHeader1.setBackground(new java.awt.Color(255, 255, 255));
        labelHeader1.setText("SISTEMA DE REPORTE DE EMPLEADOS");
        labelHeader1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelHeader1.setFont(new java.awt.Font("Engravers MT", 1, 28)); // NOI18N

        btnPlanilla.setBackground(new java.awt.Color(51, 51, 51));
        btnPlanilla.setText("PLANILLA");
        btnPlanilla.setDescription("Formulario ");
        btnPlanilla.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 48)); // NOI18N
        btnPlanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanillaActionPerformed(evt);
            }
        });

        btnRecibo.setText("Actualizar Recibo");
        btnRecibo.setDescription("Formulario");
        btnRecibo.setFont(new java.awt.Font("Franklin Gothic Heavy", 1, 48)); // NOI18N
        btnRecibo.setPreferredSize(new java.awt.Dimension(274, 64));
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboActionPerformed(evt);
            }
        });

        btnPlanilla1.setBackground(new java.awt.Color(51, 51, 51));
        btnPlanilla1.setText("SALIR");
        btnPlanilla1.setDescription("Sistema");
        btnPlanilla1.setFont(new java.awt.Font("Franklin Gothic Heavy", 3, 18)); // NOI18N
        btnPlanilla1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlanilla1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Atencion al cliente.");

        jLabel2.setText("Tel.   3144795931 - 3183340935.");

        jLabel5.setText("f/ sistemidempf@gmail.com  ig/ sistemmidpeig@gmail.com  ");

        javax.swing.GroupLayout jcMousePanel2Layout = new javax.swing.GroupLayout(jcMousePanel2);
        jcMousePanel2.setLayout(jcMousePanel2Layout);
        jcMousePanel2Layout.setHorizontalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel2Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addGroup(jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jcMousePanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jcMousePanel2Layout.createSequentialGroup()
                        .addGroup(jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlanilla1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jcMousePanel2Layout.setVerticalGroup(
            jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcMousePanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(labelHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btnPlanilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRecibo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPlanilla1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addGroup(jcMousePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlanillaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPlanillaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        VentanaPlanilla p = new VentanaPlanilla();
        p.setVisible(true);
    }// GEN-LAST:event_btnPlanillaActionPerformed

    private void btnReciboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnReciboActionPerformed
        this.setVisible(false);
        ActualizarRecibo r = new ActualizarRecibo();
        r.setVisible(true);
    }// GEN-LAST:event_btnReciboActionPerformed

    private void btnPlanilla1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPlanilla1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }// GEN-LAST:event_btnPlanilla1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTask btnPlanilla;
    private org.edisoncor.gui.button.ButtonTask btnPlanilla1;
    private org.edisoncor.gui.button.ButtonTask btnRecibo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private jcMousePanel.jcMousePanel jcMousePanel2;
    private org.edisoncor.gui.label.LabelBackgroundTitle labelBackgroundTitle1;
    private org.edisoncor.gui.label.LabelHeader labelHeader1;
    // End of variables declaration//GEN-END:variables
}
